.TH kilo 1 "January 11 2017"
.SH NAME
kilo \- small text editor
.SH SYNOPSIS
.B kilo
.RI "file"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B kilo
command.
.PP
\fBkilo\fP is just a tiny file editor with syntax highlighting and search.
.SH KEYS
CTRL-S: Save
.br
CTRL-Q: Quit
.br
CTRL-F: Find string in file (ESC to exit search, arrows to navigate)
.SH SEE ALSO
.BR emacs (1),
.BR vi (1).
